apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatwebapp
  labels:
    app: tomcatwebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcatwebapp
	    author: prakash
  template:
    metadata:
      labels:                           #labels should match with matchLabels
        app: tomcatwebapp
		    author: prakash
    spec:
      containers:
      - name: tomcatwebapp
        image: <ECR>
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcatwebapp-service
spec:
  selector:                       #should match with Deployment's template label
    app: tomcatwebapp
    author: prakash
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
 
